org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=1.18.2
yarn_mappings=1.18.2+build.4
loader_version=0.14.25

mod_version=0.1.0
maven_group=com.ezquest.astralclef
archives_base_name=astralclef

fabric_version=0.77.0+1.18.2

# Create Fabric Astral-verified; JiJ Flywheel 0.6.10-39; no 0.6.4 pin
create_version=0.5.1-f-build.1415+mc1.18.2
